USE [master]
GO

/****** Object:  Database [CongTy]    Script Date: 18/04/2018 11:52:18 AM ******/
CREATE DATABASE [CongTy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CongTy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CongTy.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CongTy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\CongTy_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CongTy] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CongTy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CongTy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CongTy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CongTy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CongTy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CongTy] SET ARITHABORT OFF 
GO

ALTER DATABASE [CongTy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CongTy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CongTy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CongTy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CongTy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CongTy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CongTy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CongTy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CongTy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CongTy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CongTy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CongTy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CongTy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CongTy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CongTy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CongTy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CongTy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CongTy] SET RECOVERY FULL 
GO

ALTER DATABASE [CongTy] SET  MULTI_USER 
GO

ALTER DATABASE [CongTy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CongTy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CongTy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CongTy] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CongTy] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CongTy] SET QUERY_STORE = OFF
GO

USE [CongTy]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CongTy] SET  READ_WRITE 
GO


--------------------------------------------------DE AN


USE [CongTy]
GO

/****** Object:  Table [dbo].[DEAN]    Script Date: 18/04/2018 11:52:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEAN](
	[MADA] [nvarchar](50) NOT NULL,
	[TENDA] [nvarchar](50) NULL,
	[DIADIEMDA] [nvarchar](50) NULL,
	[PHONG] [nvarchar](50) NULL,
 CONSTRAINT [PK_DEAN] PRIMARY KEY CLUSTERED 
(
	[MADA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DEAN]  WITH CHECK ADD  CONSTRAINT [FK_DEAN_PHONGBAN] FOREIGN KEY([PHONG])
REFERENCES [dbo].[PHONGBAN] ([MAPHONG])
GO

ALTER TABLE [dbo].[DEAN] CHECK CONSTRAINT [FK_DEAN_PHONGBAN]
GO











-------------------- DIA DIEM PHONG BAN

USE [CongTy]
GO

/****** Object:  Table [dbo].[DIADIEMPHONGBAN]    Script Date: 18/04/2018 11:52:45 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIADIEMPHONGBAN](
	[MAPHONG] [nvarchar](50) NOT NULL,
	[DIADIEM] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DIADIEMPHONGBAN] PRIMARY KEY CLUSTERED 
(
	[MAPHONG] ASC,
	[DIADIEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DIADIEMPHONGBAN]  WITH CHECK ADD  CONSTRAINT [FK_DIADIEMPHONGBAN_PHONGBAN] FOREIGN KEY([MAPHONG])
REFERENCES [dbo].[PHONGBAN] ([MAPHONG])
GO

ALTER TABLE [dbo].[DIADIEMPHONGBAN] CHECK CONSTRAINT [FK_DIADIEMPHONGBAN_PHONGBAN]
GO









--------------------NHAN VIEN



USE [CongTy]
GO

/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 18/04/2018 11:53:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [nvarchar](50) NOT NULL,
	[HONV] [nvarchar](50) NULL,
	[TENLOT] [nvarchar](50) NULL,
	[TENNV] [nvarchar](50) NULL,
	[NS] [date] NULL,
	[DIACHI] [nvarchar](50) NULL,
	[PHAI] [nvarchar](50) NULL,
	[LUONG] [float] NULL,
	[NQL] [nvarchar](50) NULL,
	[PHONG] [nvarchar](50) NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_NHANVIEN_NHANVIEN] FOREIGN KEY([NQL])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO

ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_NHANVIEN]
GO

ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_NHANVIEN_PHONGBAN] FOREIGN KEY([PHONG])
REFERENCES [dbo].[PHONGBAN] ([MAPHONG])
GO

ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_PHONGBAN]
GO













--------------------------------PHAN CONG


USE [CongTy]
GO

/****** Object:  Table [dbo].[PHANCONG]    Script Date: 18/04/2018 11:54:35 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PHANCONG](
	[MANV] [nvarchar](50) NOT NULL,
	[MADA] [nvarchar](50) NOT NULL,
	[THOIGIAN] [float] NULL,
 CONSTRAINT [PK_PHANCONG] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC,
	[MADA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PHANCONG]  WITH CHECK ADD  CONSTRAINT [FK_PHANCONG_DEAN] FOREIGN KEY([MADA])
REFERENCES [dbo].[DEAN] ([MADA])
GO

ALTER TABLE [dbo].[PHANCONG] CHECK CONSTRAINT [FK_PHANCONG_DEAN]
GO

ALTER TABLE [dbo].[PHANCONG]  WITH CHECK ADD  CONSTRAINT [FK_PHANCONG_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO

ALTER TABLE [dbo].[PHANCONG] CHECK CONSTRAINT [FK_PHANCONG_NHANVIEN]
GO










-------------------------PHONG BAN

USE [CongTy]
GO

/****** Object:  Table [dbo].[PHONGBAN]    Script Date: 18/04/2018 11:55:25 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PHONGBAN](
	[MAPHONG] [nvarchar](50) NOT NULL,
	[TENPHONG] [nvarchar](50) NULL,
	[TRUONGPHONG] [nvarchar](50) NULL,
	[NGAYNHANCHUC] [date] NULL,
 CONSTRAINT [PK_PHONGBAN] PRIMARY KEY CLUSTERED 
(
	[MAPHONG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PHONGBAN]  WITH CHECK ADD  CONSTRAINT [FK_PHONGBAN_NHANVIEN] FOREIGN KEY([TRUONGPHONG])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO

ALTER TABLE [dbo].[PHONGBAN] CHECK CONSTRAINT [FK_PHONGBAN_NHANVIEN]
GO









--------------------THAN NHAN

USE [CongTy]
GO

/****** Object:  Table [dbo].[THANNHAN]    Script Date: 18/04/2018 11:55:46 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[THANNHAN](
	[MANV] [nvarchar](50) NOT NULL,
	[TENTN] [nvarchar](50) NOT NULL,
	[PHAI] [nvarchar](50) NULL,
	[NS] [date] NULL,
	[QUANHE] [nvarchar](50) NULL,
 CONSTRAINT [PK_THANNHAN] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC,
	[TENTN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[THANNHAN]  WITH CHECK ADD  CONSTRAINT [FK_THANNHAN_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO

ALTER TABLE [dbo].[THANNHAN] CHECK CONSTRAINT [FK_THANNHAN_NHANVIEN]
GO


